# Site settings
title: Limitless
email: your-email@domain.com
description: "Shhhh, nothing happened here yet"
baseurl: ""
url: "http://limitless.com.br"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
